config/routes.rb
Rails.application.routes.draw do
  resources :fluids
  resources :nurse_notes
  resources :treatment_sheets
  resources :nurse_procedures
  resources :incident_reports
  resources :radio_test_results
  resources :lab_order_lists
  resources :medication_temps
  resources :appointments
  resources :order_requests
  resources :order_masters
  resources :bill_temps do
    resource :download, only: [:show] 
    resource :download2, only: [:show] 
  end
  resources :admissions
  resources :service_inventory_histories
  resources :bill_histories
  resources :categories
  resources :services_inventories
  resources :test_results
  resources :radiology_requests
  resources :medication_requests
  resources :lab_requests
  resources :clinic_documents
  resources :basic_med_records
  resources :assign_patients
  resources :patients
  resources :roles
  devise_for :users
  get 'home/index'

  root 'home#index'

  get '/users' => 'users#index'

  get '/users/new' => 'users#new', :as => 'new_user'
  get '/users/:id/edit' => 'users#edit', :as => 'edit_user'
  get '/users/:id' => 'users#show', :as => 'user'
  patch '/users/:id' => 'users#update', :as => 'update_user'
  patch '/patients/:id' => 'patients#update', :as => 'update_patient'
  post 'create_user' => 'users#create', as: :create_user

  post      'update_clinic_documents'                          =>     'clinic_documents#update_clinic_documents'

  get       'remove_contact'                          =>     'users#remove_contact'

  get       'patients_form'                          =>     'patients#patients_form'
  get  'show_patients'          =>     'patients#show_patients'
  get  'edit_patients'          =>     'patients#edit_patients'
  get  'edit_docs'          =>     'assign_patients#edit_docs'
  get  'assign_a_patient'          =>     'patients#assign_a_patient'
  get  'basic_medical'          =>     'assign_patients#basic_medical'
  get  'assign_a_patient2'          =>     'basic_med_records#assign_a_patient2'

  get  'procedure_list'          =>     'assign_patients#procedure_list'

  get 'view_procedure_record' =>     'nurse_procedures#view_procedure_record'

  get 'incident_form'  =>  'incident_reports#incident_form'
  get 'view_report'  =>  'incident_reports#view_report'
  

  get  'clinic_documentation'          =>     'assign_patients#clinic_documentation'
    get  'appt_documentation'          =>     'appointments#appt_documentation'
  get  'view_documentation'          =>     'assign_patients#view_documentation'
  get  'assign_lab'          =>     'assign_patients#assign_lab'
  get  'assign_med'          =>     'assign_patients#assign_med'
  get  'show_details'          =>     'assign_patients#show_details'
  get  'docs'          =>     'assign_patients#docs'
  get  'lab_docs'          =>     'lab_requests#lab_docs'
  get  'lab_form'          =>     'lab_requests#lab_form'
  get  'view_lab'          =>     'lab_requests#view_lab'
  get  'delete_lab_record'          =>     'lab_requests#delete_lab_record'
  get  'med_docs'          =>     'medication_requests#med_docs'
  get  'med_form'          =>     'medication_requests#med_form'
  get  'view_med'          =>     'medication_requests#view_med'
  get  'other_med'          =>     'medication_requests#other_med'
  get  'other_radio'          =>     'radiology_requests#other_radio'

  get  'radio_docs'          =>     'radiology_requests#radio_docs'
  get  'radio_form'          =>     'radiology_requests#radio_form'
  get  'view_radio'          =>     'radiology_requests#view_radio'
  get 'delete_radio_record'  =>     'radiology_requests#delete_radio_record'

  get  'other_lab'          =>     'lab_requests#other_lab'
  get  'lab_history'          =>     'lab_requests#lab_history'
  get  'enter_results'          =>     'lab_requests#enter_results'
  get  'lab_medical_records'          =>     'lab_requests#lab_medical_records'
  get  'enter_radio_results'   =>     'radiology_requests#enter_radio_results'
  get  'results'          =>     'test_results#results'
  get  'patient_admission'          =>     'admissions#patient_admission'
  get  'admission_doc'          =>     'admissions#admission_doc'
  get 'patient_bill'    => 'bill_histories#patient_bill'
  get 'bill_open'    => 'bill_temps#bill_open'
  get 'outstanding'   => 'bill_temps#outstanding'
  get 'paid'    => 'bill_temps#paid'
  get 'delete_bill_record'    => 'bill_temps#delete_bill_record'

  
  get 'view_note'  => 'admissions#view_note'
  get 'view_discharge_note' => 'admissions#view_discharge_note'
  get  'view_nurse_record'          =>     'basic_med_records#view_nurse_record'
  post 'assign_to_a_doctor '  =>  'assign_patients#assign_to_a_doctor'
  get  'main_test'          =>     'test_results#main_test'
  get  'indi_radio_result'          =>     'radio_test_results#indi_radio_result'
  

  get 'close_request' =>  'medication_requests#close_request'
  get 'open_request'  =>   'medication_requests#open_request'

  get 'close_request_rad' =>  'radiology_requests#close_request_rad'
  get 'open_request_rad'  =>   'radiology_requests#open_request_rad'

  get  'order_records'          =>     'order_requests#order_records'
  get  'make_order'          =>     'order_requests#make_order'
  get  'view_order'          =>     'order_requests#view_order'

  get 'delete_order_record' =>     'order_requests#delete_order_record'

  get 'add_room'    =>      'admissions#add_room'
  get 'edit_room'    =>      'admissions#edit_room'
  post 'add_a_room'    =>      'admissions#add_a_room'

  get 'discharge_patient'    =>      'admissions#discharge_patient'
  get 'discharged_list'    =>      'admissions#discharged_list'
  get 'discharged_list_nurses'    =>      'admissions#discharged_list_nurses'
  get 'nurse_admission_list' => 'admissions#nurse_admission_list'

  get 'admission_vitals' => 'admissions#admission_vitals'
  get 'discharge_note' => 'admissions#discharge_note'
  post 'a_discharge_note' => 'admissions#a_discharge_note'

  get 'nurse_admission_vitals_history' =>  'basic_med_records#nurse_admission_vitals_history'
  get 'admission_vital_graph' =>  'basic_med_records#admission_vital_graph'
  get  'admission_basic_medical'          =>     'basic_med_records#admission_basic_medical'

  get  'doctor_admission_vitals_doc'          =>     'admissions#doctor_admission_vitals_doc'
  get  'view_doctor_admission_doc'          =>     'admissions#view_doctor_admission_doc'

  get 'close_order'  =>   'order_requests#close_order'

  get 'patient_appointment' => 'appointments#patient_appointment'

  get 'reception_patient' => 'patients#reception_patient'
  post 'reception_appointment' => 'appointments#reception_appointment'
  get 'doctor_appointment' => 'appointments#doctor_appointment'

  get 'open_med_temp'  => 'medication_temps#open_med_temp'
  get 'close_med_request'   => 'medication_temps#close_med_request'
  get 'delete_med_record'   => 'medication_temps#delete_med_record'

  get 'print_bill'   => 'bill_temps#print_bill'
  get 'print_all_bill'   => 'bill_temps#print_all_bill'

  post 'basic_vitals' => 'assign_patients#basic_vitals'

  get 'import_csv_file' => 'services_inventories#import_csv_file', as: :import_csv_file
  post 'import' => 'services_inventories#import', as: :import
  
    
  
   get  'view_vitals'          =>     'assign_patients#view_vitals'

   get 'print_labresults'   => 'lab_requests#print_labresults'
   get 'print_pharmacy'   => 'bill_temps#print_labresults'
   get 'print_xray'   => 'bill_temps#print_labresults'
   get 'print_ultrasound'   => 'bill_temps#print_labresults'

   get 'view_reciept'   => 'bill_temps#view_reciept'

   get 'set_orders'   => 'home#set_orders'

   get 'patient_profile'   => 'patients#patient_profile'

    get 'patient_treatment' => 'treatment_sheets#patient_treatment'
   get 'new_treatment' => 'treatment_sheets#new_treatment'

   get 'nurses_note' => 'basic_med_records#nurses_note'

   get 'new_nurse_note' => 'basic_med_records#new_nurse_note'
   get 'open_note' => 'basic_med_records#open_note'

   get 'fluids_intake' => 'fluids#fluids_intake'

   get 'new_fluids_intake' => 'fluids#new_fluids_intake'

end

app/models/incident_report.rb
class IncidentReport < ActiveRecord::Base
end

app/controllers/incident_reports_controller.rb
class IncidentReportsController < ApplicationController
  before_action :set_incident_report, only: [:show, :edit, :update, :destroy]

  # GET /incident_reports
  # GET /incident_reports.json
  def index
    @incident_report = IncidentReport.new
    @incident_reports = IncidentReport.joins("INNER JOIN users ON users.id = incident_reports.user_id").select('incident_reports.id,incident_type,incidate_date,incident_description,action_taken,fullname,username').where(user_id: current_user.id).order('incidate_date desc')
     #@incident_reportss = IncidentReport.all
  end


   def incident_form
   
    @incident_report = IncidentReport.new

    respond_to do |format|

      format.html
      format.js
    end
  end

  def view_report

    incident_id =params[:id]

     logger.info "incident1: #{incident_id}"

    @incident1 = IncidentReport.find_by(id: incident_id)
    

    logger.info "incident1: #{@incident1}"
   
  end

  # GET /incident_reports/1
  # GET /incident_reports/1.json
  def show
  end

  # GET /incident_reports/new
  def new
    @incident_report = IncidentReport.new
  end

  # GET /incident_reports/1/edit
  def edit
  end

  # POST /incident_reports
  # POST /incident_reports.json
  def create
    @incident_report = IncidentReport.new(incident_report_params)

    respond_to do |format|
      if @incident_report.save
        format.html { redirect_to incident_reports_path, notice: 'Incident report was successfully created.' }
        format.json { render :show, status: :created, location: @incident_report }
      else
        format.html { render :new }
        format.json { render json: @incident_report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /incident_reports/1
  # PATCH/PUT /incident_reports/1.json
  def update
    respond_to do |format|
      if @incident_report.update(incident_report_params)
        format.html { redirect_to @incident_report, notice: 'Incident report was successfully updated.' }
        format.json { render :show, status: :ok, location: @incident_report }
      else
        format.html { render :edit }
        format.json { render json: @incident_report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /incident_reports/1
  # DELETE /incident_reports/1.json
  def destroy
    @incident_report.destroy
    respond_to do |format|
      format.html { redirect_to incident_reports_url, notice: 'Incident report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_incident_report
      @incident_report = IncidentReport.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def incident_report_params
      params.require(:incident_report).permit(:user_id,:incident_type, :incidate_date, :incident_description, :action_taken, :status)
    end
end

app/helpers/incident_reports_helper.rb
module IncidentReportsHelper
end

app/views/incident_reports/_form.html.erb
<%= simple_form_for(@incident_report) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :incident_type %>
    <%= f.input :incidate_date %>
    <%= f.input :incident_description %>
    <%= f.input :action_taken %>
    <%= f.input :status %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/incident_reports/_incident_form.html.erb
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script> 
<div class="table-agile-info">

	<%= simple_form_for(@incident_report) do |f| %>
	<%= f.error_notification %>
	<%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

<div class="input-row">
	<div class="input-width">

		
		<%= f.input :incident_type, :collection => %w[Clinical Non-Clinical ] %>
	</div>

	<div class="input-width">

		<%= f.input :incidate_date, label: "Incidate Date", as: :string,input_html: { id: "datetimepicker",placeholder: 'dd-mm-yy' }  %>
	</div>



	<div class="ggg">

		<%= f.input :incident_description,label: "Describe Incident", as: :text, input_html: { rows: "4",placeholder: 'Address'}  %>

	</div>

	<div class="ggg">

		<%= f.input :action_taken,label: "Action Taken", as: :text, input_html: { rows: "4",placeholder: 'Address'}  %>

	</div>

	<br />

<div class="form-inputs">
	<%= f.input :user_id, :as=> :hidden, input_html: {value: current_user.id} %>
</div>
<div class="form-inputs">
	<%= f.input :status, :as=> :hidden, input_html: {value: 1 } %>

</div>


</div>

<center>

	<div >
		<%= f.button :submit,"Submit Report", :class => 'btn-success',:style=>"width:auto;" %>

	</div>
</center>

<% end %>

</div>



<script type="text/javascript">
				$('#datetimepicker').datetimepicker({
					format : 'DD-MM-YYYY'
				})
				$('[data-behaviour~=datetimepicker]').datetimepicker();
			</script> 


app/views/incident_reports/_view_report.html.erb




<div class="table-agile-info">



  
 <table class="custab table table-striped table-hover table-bordered">

          <tr>
            <% if (defined?(@incident1)).nil? %>
                  <% else  %>

       

            <td style="background-color:rgba(110, 129, 149, 0.96);color:#fbfbff">Incident Type</td>
            <td style="background-color:rgba(251, 251, 255, 0.96);color:#000000"><%=   @incident1.incident_type %></td>
          </tr>
           <tr>
            <td style="background-color:rgba(110, 129, 149, 0.96);color:#fbfbff">Description</td>
            <td style="background-color:rgba(251, 251, 255, 0.96);color:#000000"><%=   @incident1.incident_description %></td>
          </tr>
           
            <tr>
            <td style="background-color:rgba(110, 129, 149, 0.96);color:#fbfbff">Action Taken</td>
            <td style="background-color:rgba(251, 251, 255, 0.96);color:#000000"><%=   @incident1.action_taken %></td>
          </tr>

           
               <tr>
            <td style="background-color:rgba(110, 129, 149, 0.96);color:#fbfbff">Date</td>
            <td style="background-color:rgba(251, 251, 255, 0.96);color:#000000"><%=   @incident1.created_at %></td>
              </tr>
         
 <% end %>

          
         
           </table>


</div>








app/views/incident_reports/edit.html.erb
<h1>Editing Incident Report</h1>

<%= render 'form' %>

<%= link_to 'Show', @incident_report %> |
<%= link_to 'Back', incident_reports_path %>

app/views/incident_reports/incident_form.js.erb

$("#incident_form").html("<%= escape_javascript(render 'incident_reports/incident_form') %>");

 $('#modal-window').modal('show');

app/views/incident_reports/index.html.erb
<section id="main-content">
  <section class="wrapper">

    <fieldset>
      <div class="row2 col-md-8 col-md-offset-1 custyle">
        <div class="row2">
          <div class="container">
            <div class="card-container.card"
            <div class="col-md-10  col-md-offset-1">

            </div>
            </div>
            </div>
            </div>
            </div>
            </fieldset>

            <div class="table-agile-info">
            <div class="panel panel-default">
            <div class="panel-heading">
            Incident Reports
            </div>
            <div style="overflow-x:auto;">
            <table class="table" ui-jq="footable" ui-options='{
            "paging": {
            "enabled": true
            },
            "filtering": {
            "enabled": true
            },
            "sorting": {
            "enabled": true
            }}'>
            <thead>
            <tr>

             <th>No</th>
           <th>Incident type</th>
      <th> Date of Incident</th>
      <th> Description</th>
      <th>Action taken</th>
    
           
            
            </tr>
            </thead>
            <tbody>
            <% count=1 %>

            

            <% @incident_reports.each do |incident_report| %>
            <tr>

            <td><%= count %></td>
           <td><%= incident_report.incident_type %></td>
        <td><%= incident_report.incidate_date %></td>
        <td><%= incident_report.incident_description %></td>
        <td><%= incident_report.action_taken %></td>
      

          

          

            <td ><%= link_to 'View Full Report', view_report_path(:id => incident_report.id), {:remote => true, class:'"btn btn-primary btn-sm btn3d"','data-toggle' =>  "modal", 'data-target' => '#myModal5'} %></td>

              </tr>

              <% count=count+1 %> 

              <% end %>

              </tbody>

              </table>
             

              <center>
                <%= link_to  '<i class="fa fa-plus"></i> &nbsp; New Incident Report'.html_safe, incident_form_path, {:remote => true, :class => "btn btn-danger btn-sm" ,'data-toggle' =>  "modal", 'data-target' => '#myModal'} %>
            
                </center>
              <br>

            </div>
          </div>
        </div>
  </section>

</section>

<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">
          &times;
        </button>
        <h4 class="modal-title"> Create Incident Report</h4>
      </div>
      <div class="modal-body" id = 'incident_form'>
        <%= render "incident_form" %>
      </div>

    </div>

  </div>
</div>

<div id="myModal5" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content" >
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">
          &times;
        </button>
        <h4 class="modal-title"> Full Report</h4>
      </div>
      <div class="modal-body" id = 'hey'>
        <%= render "view_report" %>
      </div>

    </div>

  </div>
</div>

app/views/incident_reports/new.html.erb
<h1>New Incident Report</h1>

<%= render 'form' %>

<%= link_to 'Back', incident_reports_path %>

app/views/incident_reports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Incident type:</strong>
  <%= @incident_report.incident_type %>
</p>

<p>
  <strong>Incidate date:</strong>
  <%= @incident_report.incidate_date %>
</p>

<p>
  <strong>Incident description:</strong>
  <%= @incident_report.incident_description %>
</p>

<p>
  <strong>Action taken:</strong>
  <%= @incident_report.action_taken %>
</p>

<p>
  <strong>Status:</strong>
  <%= @incident_report.status %>
</p>

<%= link_to 'Edit', edit_incident_report_path(@incident_report) %> |
<%= link_to 'Back', incident_reports_path %>

app/views/incident_reports/view_report.js.erb


$("#hey").html("<%= escape_javascript(render 'incident_reports/view_report') %>");
 $('#modal-window').modal('show');